name: my intro
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]

  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master"]}
jobs:
  # metrics-main:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # See action.yml for all options
  #     - uses: lowlighter/metrics@master
  #       with:
  #         # Your GitHub token
  #         filename: metrics-main.svg
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         base: header, activity, community, repositories, metadata
  #         template: classic

  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "auto update"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
